//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igooana.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Igooana.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;kind&quot;:&quot;analytics#profiles&quot;,&quot;username&quot;:&quot;iamvalentin@gmail.com&quot;,&quot;totalResults&quot;:2,&quot;startIndex&quot;:1,&quot;itemsPerPage&quot;:1000,&quot;items&quot;:[{&quot;id&quot;:&quot;55921002&quot;,&quot;kind&quot;:&quot;analytics#profile&quot;,&quot;selfLink&quot;:&quot;https://www.googleapis.com/analytics/v3/management/accounts/29000446/webproperties/UA-29000446-1/profiles/55921002&quot;,&quot;accountId&quot;:&quot;29000446&quot;,&quot;webPropertyId&quot;:&quot;UA-29000446-1&quot;,&quot;internalWebPropertyId&quot;:&quot;54947842&quot;,&quot;name&quot;:&quot;g.raphael-radar&quot;,&quot;currency&quot;:&quot;USD&quot;,&quot;timezone&quot;:&quot;America/Los_Angeles&quot;,&quot;websiteUrl&quot;:&quot;http://valve.github.com/g.raphael-ra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManagementProfilesJson {
            get {
                return ResourceManager.GetString("ManagementProfilesJson", resourceCulture);
            }
        }
    }
}
